name: pages-build-deployment

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      
      - uses: docker://pandoc/core:2.9
        with:
          args: "-f markdown-smart+autolink_bare_uris --template index.tmpl index.md -o index.html"
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: master # The branch the action should deploy to.
          folder: . # The folder the action should deploy.